/**
 * Pre-generated scenario data for all conferences.
 * This file is auto-generated by `bun run generate`.
 * DO NOT EDIT MANUALLY.
 */

import type { Scenario, Game } from "@types";
import type { GameOutcome } from "./scenarioAnalysis";

// Serialized version of TeamRequirements (with arrays instead of Sets)
export interface SerializedTeamRequirements {
  team: string;
  totalScenarios: number;
  top2Count: number;
  sufficientConditions: Array<{
    outcomes: GameOutcome[];
    guaranteedScenarios: number;
    scenarioIndices?: number[];
  }>;
  blockingConditions: Array<{
    outcomes: GameOutcome[];
    blockedScenarios: number;
    scenarioIndices?: number[];
  }>;
}

export interface ScenarioData {
  scenarios: Scenario[];
  generatedAt: string;
  unplayedGames: Game[];
  teamRequirements: Record<string, SerializedTeamRequirements>;
}

// Import pre-generated cache files
import aacData from "../data/cache/aac_scenarios.json";
import accData from "../data/cache/acc_scenarios.json";
import big10Data from "../data/cache/big10_scenarios.json";
import big12Data from "../data/cache/big12_scenarios.json";
import secData from "../data/cache/sec_scenarios.json";

// Type assertion for the imported JSON data
const scenarioCache: Record<string, ScenarioData> = {
  AAC: aacData as unknown as ScenarioData,
  ACC: accData as unknown as ScenarioData,
  Big10: big10Data as unknown as ScenarioData,
  Big12: big12Data as unknown as ScenarioData,
  SEC: secData as unknown as ScenarioData,
};

export function getScenarioData(confKey: string): ScenarioData | null {
  return scenarioCache[confKey] ?? null;
}

export function getAllConferenceKeys(): string[] {
  return Object.keys(scenarioCache);
}
